name: Run ETL every 2 minutes

on:
  schedule:
    - cron: '*/6 * * * *'  # Runs every 2 minutes
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run ETL script
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
      run: python etl.py

    - name: Debug - Check token length
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_PAT }}
      run: |
        echo "Token length: ${#GITHUB_TOKEN}"  # Should return a non-zero length
      shell: bash

    - name: Debug - Show first 4 chars of token
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_PAT }}
      run: |
        echo "Token starts with: ${GITHUB_TOKEN::4}"  # Should print first 4 characters
      shell: bash

    - name: Debug - Set remote URL for GitHub
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_PAT }}
      run: |
        git remote set-url origin https://${{ secrets.PUSH_PAT }}@github.com/${{ github.repository }}
        git remote -v  # Verify the remote URL
      shell: bash

    - name: Commit and push updated CSV
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add data/news_data.csv

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🔄 Auto update news data"
          git push origin HEAD:main
        fi
      shell: bash