name: Run ETL every 6 hours

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run ETL script
      env:
        GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}
      run: python etl.py

    - name: Commit and push updated CSV
      env:
        GITHUB_TOKEN: ${{ secrets.PUSH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
        git add data/news_data.csv
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🔄 Auto update news data"
          git push origin HEAD:main
        fi